// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugfsvhceoqgvaoganyoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZnN2aGNlb3FndmFvZ2FueW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTM5NTQsImV4cCI6MjA2NzY2OTk1NH0.jVlqMM4z2IBGXmWWXOZgCJ8UFwHQ346p2x36PgxUxLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});